import "Enums/SignUpResult.idl";

namespace Steamfinity.Services
{
	[bindable]
	[default_interface]
	runtimeclass SteamfinityCloud
	{
		SteamfinityCloud();

		Windows.Foundation.IAsyncOperation<Steamfinity.Enums.SignUpResult> SignUpAsync(String userName, String password);
	}
}
